language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pandoc devscripts debhelper python-setuptools

install:
  - pip install --no-deps -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - python setup.py test
  - find -type f -name "*.py" | grep -v build | xargs flake8 --ignore=E402

after_success:
  - coverage run --source woudc_formats setup.py test
  - coverage report -m
  - debuild -b -uc -us

